### ISSUE TITLE
ModuleNotFoundError: No module named 'stimer'

### ISSUE THREAD

**Issue by devhci** [Unisens/pyunisens#2]
Hi ,

I am getting error No module named 'stimer'

` File "/Users/deku/PycharmProjects/createData/venv/lib/python3.7/site-packages/unisens/__init__.py", line 2, in <module>
    from .main import Unisens
  File "/Users/deku/PycharmProjects/createData/venv/lib/python3.7/site-packages/unisens/main.py", line 32, in <module>
    import stimer`

installed pyunisens  via  pip install git+https://github.com/Unisens/pyunisens
python 3.7

**Comment by skjerns** [comment]
My bad. just uncomment the line or reinstall, I've fixed it. That is just some debugging package

**Comment by devhci** [comment]
I tried doing commenting the line  but then it gives  below error

`Traceback (most recent call last):
  File "/Users/deku/PycharmProjects/createData/main.py", line 23, in <module>
    print(u)
  File "/Users/deku/PycharmProjects/createData/venv/lib/python3.7/site-packages/unisens/main.py", line 109, in __str__
    duration = str(datetime.timedelta(seconds=int(duration)))
ValueError: invalid literal for int() with base 10: '324481.0'`

**Comment by skjerns** [comment]
Ok. That should be a harmless incompatability, try again, I've updated

**Comment by devhci** [comment]
Its fixed now. :) Thanks
