### ISSUE TITLE
Issue with the creating new file--garbage upscaled values are entered in the new file  

### ISSUE THREAD

**Issue by devhci** [Unisens/pyunisens#3]
When I create a new file  and then read it it gives  garbage upscaled values that I did not enter.
Please see the below example 
Create  new File 

```
 newUnisens = unisens.Unisens('/Users/deku/Desktop/unisens_data/new2/hh',duration=3600,timestampStart='2019-11-19T09:39:06.000',measurementId="measurementId",makenew=True, autosave=True, readonly=False)
   
   signal = np.random.rand(1, 1024*3600)
    print(signal)
    SignalEntry(id='ecg.bin', parent =newUnisens).set_data(signal, sampleRate=1024, contentClass='ecg',ch_names=['ECG I'],dataType="int16",unit="mV",adcResolution="16", baseline="2048")

    newUnisens.save()
```
### File gets create  and the values that I entered as signal were

[[0.30714025 0.25306972 0.87095374 ... 0.160702   0.45849608 0.8259927 ]]

However, When I am trying to read that file it don't give me the same vales that I have entered--- It some how upscales the entries 

```
read= unisens.Unisens('/Users/deku/Desktop/unisens_data/new2/hh')
s = read['ecg.bin']
d= s.get_data()   
print(d.size)
print(d)
```
###Out put 
[[ 11184. -26328. -12184. ...  -8569.  26856.  16366.]]

### Code snippet for reproducibility 

```
import unisens 
import numpy as np
from unisens import SignalEntry

newUnisens = unisens.Unisens('/Users/deku/Desktop/unisens_data/new2/hh',duration=30,timestampStart='2019-11-19T09:39:06.000',measurementId="measurementId",makenew=True, autosave=True, readonly=False)

         
signal = np.random.rand(1, 1024*30)

print("signal size " +str(signal.size))
print("Signal that I entered in the ecg.bin file")

print(signal)
SignalEntry(id='ecg.bin', parent =newUnisens).set_data(signal, sampleRate=1024, contentClass='ecg',ch_names=['ECG I'],dataType="int16",unit="mV",adcResolution="16", baseline="2048")

newUnisens.save()


read= unisens.Unisens('/Users/deku/Desktop/unisens_data/new2/hh')
s = read['ecg.bin']
d= s.get_data()
#d = d[0]   

print("\nOutput I get when reading the file I just created ")
print("signal Size= " + str(d.size))
print(d)

**Comment by skjerns** [comment]
My first hunch is that you create the signal as a float (`np.random.rand` creates floats), but force the program to save the data as int16. Change dataType="float64" or use `np.random.randint()`

You can actually leave the `dataType=...` out entirely, as `pyunisens` will infer the datatype automatically

**Comment by devhci** [comment]
Ah! goodness. Thanks @skjerns. Actuality the  unisens.xml file that I was reading has  ECG dataType defined  as int16  but 
 still gives ECG values as float16 array. I got confused.

**Comment by jottenbacher** [comment]
Hi,

conversion to float should only happen with readScaled(). Normal read() function should return the values in the datatype specified.

Cheers
Jörg



--
Dr.-Ing. Jörg Ottenbacher
movisens GmbH

Augartenstraße 1
D-76137 Karlsruhe
Tel.: +49 (721) 381344-11
Fax: +49 (721) 381344-90
ottenbacher@movisens.com
www.movisens.com<http://www.movisens.com>

Registergericht: Amtsgericht Mannheim, HRB 708200, Sitz der Gesellschaft: Karlsruhe
Geschäftsführer: Ulrich Großmann, Jörg Ottenbacher
<https://twitter.com/movisens>


________________________________
Von: skjerns <notifications@github.com>
Gesendet: Donnerstag, 10. September 2020 19:26
An: Unisens/pyunisens <pyunisens@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [Unisens/pyunisens] Issue with the creating new file--garbage upscaled values are entered in the new file (#3)


Oh, it does? that sounds more like an error.

So in the unisens.xml it's defined as int16, and in the .bin file it is stored as int16, but pyunisens loads it as float? that should not happen. Although it might happen, if the lsbValue is provided - then it will automatically convert from ADC values to other units.

**Comment by devhci** [comment]
> So in the unisens.xml it's defined as int16, and in the .bin file it is stored as int16, but `pyunisens` loads it as float?

No, I ECG was stored as float in .bin itself.  It's only the unisens.xml which says dtype as int16--  but in reality data is stored as float.

**Comment by jottenbacher** [comment]
How can some bytes of float be distiguished from some bytes of int16 without any further information?
At least unisens datasets containing datafiles (*.bin) with datatypes that do not correspond to the entry definiton in unisens.xml should not exist.


--
Dr.-Ing. Jörg Ottenbacher
movisens GmbH

Augartenstraße 1
D-76137 Karlsruhe
Tel.: +49 (721) 381344-11
Fax: +49 (721) 381344-90
ottenbacher@movisens.com
www.movisens.com<http://www.movisens.com>

Registergericht: Amtsgericht Mannheim, HRB 708200, Sitz der Gesellschaft: Karlsruhe
Geschäftsführer: Ulrich Großmann, Jörg Ottenbacher
<https://twitter.com/movisens>


________________________________
Von: Devender kumar <notifications@github.com>
Gesendet: Montag, 14. September 2020 14:32
An: Unisens/pyunisens <pyunisens@noreply.github.com>
Cc: Jörg Ottenbacher <joerg.ottenbacher@movisens.com>; Comment <comment@noreply.github.com>
Betreff: Re: [Unisens/pyunisens] Issue with the creating new file--garbage upscaled values are entered in the new file (#3)


So in the unisens.xml it's defined as int16, and in the .bin file it is stored as int16, but pyunisens loads it as float?

No, I ECG was stored as float in .bin itself. It's only the unisens.xml which says dtype as int16-- but in reality data is stored as float.

**Comment by skjerns** [comment]
> Hi, conversion to float should only happen with readScaled(). Normal read() function should return the values in the datatype specified. Cheers Jörg

This is only true for the Java version.

In Python, if you supply `scaled=True` it will rescale them accordingly. If you want raw ADC values, just put `scaled=False`. So the `.bin` file certainly contains `int16`, but is rescaled, as `scaled=True` is the default option (as it should be in my opinion).

**Comment by devhci** [comment]
Hi @skjerns 

I have large unisens file which I extract from device.  I chop this large file to smaller files using this python  library. The  total size(in GB) of all these chopped files  is almost doubles of the  of the original file. Does this has something to do with compression? 


My understanding is that since the large recording was extracted from a ECG device which must be using  some compression technique in the .bin files whereas this library does not do any compression etc or the new unisens files.  Is my interpretation correct    or Am I doing something wrong? I checked the signal duration and quality etc in all he smaller files ---everything seems to be machining the original large file as it is.

**Comment by skjerns** [comment]
Binary usually states that the data is stored as-is, e.g. with data as 0 and 1 as in memory. It is possible, that the ECG device stores data compressed, however, I do not think that this is the case. If the data is saved in unisens format it is not compressed (otherwise it could not be read by `pyunisens`). 

If the data is close to exactly double, it is more likely that the data is actually saved as INT16, but you store it as INT32 (or any equivalent, e.g. INT32/INT64, FLOAT/DOUBLE, etc). That would perfectly explain the doubleing of size. Depending on the ADC resolution you can safely store the data sometimes even as INT8 and save even more space ;-)

**Comment by devhci** [comment]
@skjerns Thanks . I think it explains it well. I changed the data type from 16 to 32. Will switch back to 16.
