### ISSUE TITLE
Add new custom attributes

### ISSUE THREAD

**Issue by JoshM94** [Unisens/pyunisens#4]
Hi,
I want to add a new custom attribute with one key & one value as result in unisens. I tried different code. The following overwrites all custom attributes and adds only the new one.

```
from unisens import CustomAttributes
import unisens as uni

unisens = uni.Unisens('C:/Users/Josua/Desktop/example1')    # in this folder is a unisens file
value_ecg_hr_inactive = 101.0              # usually i get the values from a dataframe, but it doesn't matter here

unisens.add_entry(CustomAttributes(key='ecg_hr_inactive', value=value_ecg_hr_inactive))  # overwrites all custom attributes, which are listed before. Only the new custom attribute is added.
unisens.save()
```

I also tried other code with MiscEntry as Input of add_entry

```
from unisens import MiscEntry
import unisens as uni

unisens = uni.Unisens('C:/Users/Josua/Desktop/example1')
value_ecg_hr_inactive = 101.0

hr_inactive_miscentry = MiscEntry(name='customAttribute', key='ecg_hr_inactive', value=str(value_ecg_hr_inactive))
CustomAttributes(key='ecg_hr_inactive', value=value_ecg_hr_inactive).add_entry(hr_inactive_miscentry)
unisens.save()
```
There I get an error --> AttributeError: 'MiscEntry' object has no attribute 'key'

Can you explain me the correct code to adding new custom attributes by keeping the old custom attributes?

Thanks,
Josua

**Comment by skjerns** [comment]
The following code works for me
```Python
u = unisens.Unisens('example1')
c = unisens.CustomAttributes(key='ecg_hy_inactive', value=101.0)
u.add_entry(c)
u.save()
```

If you do not want to overwrite the existing custom attributes, you need to access the already existing one and add it to there, else it will be overwritten. You can also access attributes with generic Python syntax

```Python
u = unisens.Unisens('z:/example1')
c = unisens.CustomAttributes(key='key1', value='value1')
u.add_entry(c)
u.save()

u = unisens.Unisens('z:/example1')
u.customAttributes.key2 = 'value2' # uses generic Python syntax
u.save()
```

**Comment by JoshM94** [comment]
I'm not sure if this is what you meant. But this worked great for me. Only the new parameter is added, the old parameters still exist in the unisens file.

```
u = Unisens('C:/Users/Josua/Desktop/example1')

value = 100
u.CustomAttributes.new_key = value
u.save()
```

**Comment by skjerns** [comment]
perfect, so it solved your problem?

**Comment by JoshM94** [comment]
Yes, thanks for your help.
